### PR TITLE
Broken Pickaxe

### PR DESCRIPTION
**Pull request by Lajnux**
### Description:

Added Ore Pack and Broken Pickaxe to VM

### Changes:

Added Ore Pack and Broken Pickaxe to VM

### Other checks:

- [x] I have tested all my changes thoroughly.

### CODE REVIEW

**Comment by nwjgit** [comment]
I would recommend this be handled in a different way. The Ore Pack from volcanic mine is an actual item in-game: https://oldschool.runescape.wiki/w/Ore_pack_(Volcanic_Mine) . This code auto gives the loot from the ore pack when purchased. 

This would remove alot of functionality and user experience such as:
- `/lb opens openable:`
- `/data name:Personal Open Stats`
- Bank log
- Sac log
- No functionality to the ore pack in BSO when received from a mystery box.

Having an openable function differently than 99% of other openables probably isn't the way to go. 
There is already a way to easily handle openables with oldschooljs. Trying to re-invent the wheel here would just add to player confusion and frustration in my opinion.

**Comment by Lajnux** [comment]
I don't agree with this,
It adds extra unnecessary steps for the user.
We already have Ore Pack from Giant's Foundry and would have to separate them.
The Ore Pack doesn't have a CL itself, Giant's Foundry one does.
There is plenty of items that are unopenable in BSO, making extra work for a mystery box item to be openable isn't really a priority.

**Comment by nwjgit** [comment]
> I don't agree with this, It adds extra unnecessary steps for the user. We already have Ore Pack from Giant's Foundry and would have to separate them. The Ore Pack doesn't have a CL itself, Giant's Foundry one does. There is plenty of items that are unopenable in BSO, making extra work for a mystery box item to be openable isn't really a priority.

Why make this one openable function differently than 99% of the other ones though?

**Comment by TastyPumPum** [comment]
Dragon Pickaxe broken has been added in: https://github.com/oldschoolgg/oldschoolbot/pull/5709

**Pull request closed without merging**
