### PR TITLE
Added energy bank filter

### PR DESCRIPTION
**Pull request by TURB042O**
### Description:

- added energy to bank filters

### Changes:

- made it so energy can have uppercase & lowercase E
- made alias "en"

### Other checks:

- [ ] I have tested all my changes thoroughly.

### CODE REVIEW

**Comment by TURB042O** [comment]
[Divination Issue Thread #5602](https://github.com/oldschoolgg/oldschoolbot/issues/5602#issue-2101000368)

**Comment by gc** [comment]
This needs to be generated dynamically from the energy list.

**Comment by nwjgit** [comment]
```
const energy = divinationEnergies.flatMap(i => i.item.id);
```

Will work as a dynamic solution. Just be sure to update imports and lint.

**Comment by TURB042O** [comment]
> This needs to be generated dynamically from the energy list.

done. thank you @nwjgit

**Comment by TURB042O** [comment]
> This needs to be generated dynamically from the energy list.

I added what jonesy posted and added the import

**Pull request closed without merging**
