### PR TITLE
Added Divination CL

### PR DESCRIPTION
**Pull request by TURB042O**
### Description:

Divination CL with energies, portents, outfit, egg, pet, jar & invention items

### Other checks:

- [ ] I have tested all my changes thoroughly.

### CODE REVIEW

**Comment by TURB042O** [comment]
otherwise there is this option
this was how I first started to do it

```js
export const divinationCL = resolveItems([
    'Pale energy',
    'Flickering energy',
    'Bright energy',
    'Glowing energy',
    'Sparkling energy',
    'Gleaming energy',
    'Vibrant energy',
    'Lustrous energy',
    'Elder energy',
    'Brilliant energy',
    'Radiant energy',
    'Luminous energy',
    'Incandescent energy',
    'Ancient energy',
    'Doopy',
    'Jar of memories',
    'Divine egg',
    "Wisp-buster",
    'Divine hand',
    ...divinersOutfit,
    ...divBoons,
    ...divPortents
]);

const divBoons = resolveItems([
    'Boon of pale energy',
    'Boon of flickering energy',
    'Boon of bright energy',
    'Boon of glowing energy',
    'Boon of sparkling energy',
    'Boon of gleaming energy',
    'Boon of vibrant energy',
    'Boon of lustrous energy',
    'Boon of elder energy',
    'Boon of brilliant energy',
    'Boon of radiant energy',
    'Luminous energy',
    'Incandescent energy',
    'Boon of ancient energy'
]);

const divPortents = resolveItems([
    'Cache portent',
    'Graceful portent',
    'Rogues portent',
    'Dungeon portent',
    'Lucky portent',
    'Rebirth portent',
    'Spiritual mining portent',
    'Pacifist hunting portent'
]);
```

**Comment by TURB042O** [comment]
or would this work
```js
import { divinationEnergies, portents } from '../bso/divination';

export const divinationCL = resolveItems([
     'Pale energy',
     'Flickering energy',
     'Bright energy',
     'Glowing energy',
     'Sparkling energy',
     'Gleaming energy',
     'Vibrant energy',
     'Lustrous energy',
     'Elder energy',
     'Brilliant energy',
     'Radiant energy',
     'Luminous energy',
     'Incandescent energy',
     'Ancient energy',
     'Doopy',
     'Jar of memories',
     'Divine egg',
     "Wisp-buster",
    'Divine hand',
    ...divinersOutfit,
    ...portents,
    ...divinationEnergies
```

**Comment by TURB042O** [comment]
or would this work better?
```js
import { divinationEnergies, portents } from '../bso/divination';

export const divinationCL = resolveItems([
	'Doopy',
	'Jar of memories',
	'Divine egg',
	"Wisp-buster",
	'Divine hand',
	...divinersOutfit,
	...portents.map(p => p.item.id),
	...divinationEnergies
		.map(i => [i.boon?.id, i.item.id])
		.flat(1)
		.filter(notEmpty)
```

**Comment by nwjgit** [comment]
Divination cl has already been coded and merged here https://github.com/oldschoolgg/oldschoolbot/commit/e2434658dc916769512e9c24bf1223b89005cb8e

It will be live next update

**Pull request closed without merging**
