### PR TITLE
integrity change

### PR DESCRIPTION
**Pull request by wyattos**
### Description:

i get to actually use the perks i earned lmao

-   [] I have tested all my changes thoroughly.

### CODE REVIEW

**Comment by wyattos** [comment]
also pretty sure this would fix the cache issue for contributors and mods if mods were given a badge

**Comment by wyattos** [comment]
since alex loves shit talking my prs im pretty sure this is the full solution:
just make it check badges not bitfields, it automatically removes badges at the end of the month and as we've seen before badges obviously stay even if theyre uncached and shown as (unknown) on the leaderboards https://imgur.com/a/0tcq3Xr

**Comment by wyattos** [comment]
i post something that may be the solution to a problem people wah about all the time and you bitch about that? LMFAO boo hoo

**Comment by gc** [comment]
If we're checking bitfield then we don't need to bother to check for contributor role anymore.

You are still being childish and aggressive for no reason. You need to adjust your attitude. If you can behave like a reasonable and respectful person, I would happily tell alex to shut up and not disrespect you.

**Comment by wyattos** [comment]
cant request review (not you alex, dont even click this)

**Comment by gc** [comment]
I don't understand why you just made a big random change (with no explanation), instead of just the thing I said.

**Comment by gc** [comment]
Fixed in https://github.com/oldschoolgg/oldschoolbot/pull/727

**Pull request closed without merging**
