### PR TITLE
Update rates - finish pets

### PR DESCRIPTION
**Pull request by TastyPumPum**
Update the finish pets to the more common methods of obtaining the pets.

### CODE REVIEW

**Comment by gc** [comment]
These were coded as being the most common training methods, not the most common methods of farming pets, which are usually NOT the most common training methods. And most people just get pets from their regular training methods.

**Comment by TastyPumPum** [comment]
> These were coded as being the most common training methods, not the most common methods of farming pets, which are usually NOT the most common training methods. And most people just get pets from their regular training methods.

Think it's rare people chop magic trees or fish monkfish anymore really but understandable I just made the pr as it was suggested to update them as they're outdated really.

**Comment by gc** [comment]
Mind runes and volcanic mine?

**Comment by 6enny6** [comment]
most people do not get the pets from regular training methods, you dont even get close to the rates by having 99 in a skill. So post 99 you would go for the farming pet methods,. 

These rates are taken from the osrs petcord (a server showing the quickest way to get each pet) and excluding any alt or tick manipulation methods. See mind runes and VM below.

image

image

**Comment by 6enny6** [comment]
maybe we could add a method: option? or something similar

/finish input:Heron pet method:Karambwans

for example

**Comment by gc** [comment]
Like I said though, these were coded as being the "meta way to hunt pets", they're coded as being the most recognizable, common places that people get them.

**Pull request closed without merging**
