### PR TITLE
added Long bone and Curved bone to prayer

### PR DESCRIPTION
**Pull request by 00justas**
### Description:

- added Long bone and Curved bone to prayer

### Changes:

- added Long bone and Curved bone to prayer

### Other checks:

- [X] I have tested all my changes thoroughly.

### CODE REVIEW

**Comment by gc** [comment]
What is the purpose/reason for this?

**Comment by 00justas** [comment]
Its a missing option/feature from osrs. Divine waters also use this array list in bso and it was requested to add these to the divine water list

**Comment by DayV-git** [comment]
This would put long and curved bones twice in /offer with two different meanings

**Comment by nwjgit** [comment]
> This would put long and curved bones twice in /offer with two different meanings

This wouldn't be the case,
`offerables` under offer.ts is a set so it will only list long and curved bone once. long and curved bone are also listed under `specialBones` and are handled first.

**Comment by gc** [comment]
Can you check that its not the case? My worry is just that people will accidentally offer/bury these bones, and theres literally no purpose ever for this in OSB. If someone comes along and accidentally does a /bury trip of all their saved up long bones, they wont be happy. So maybe its better off just in bso.

**Comment by nwjgit** [comment]
> Can you check that its not the case? My worry is just that people will accidentally offer/bury these bones, and theres literally no purpose ever for this in OSB. If someone comes along and accidentally does a /bury trip of all their saved up long bones, they wont be happy. So maybe its better off just in bso.

I tested it and my comment above is correct, but you do bring up a good point. It might be more beneficial to just add to the divine water array manually in bso rather than this approach.

**Comment by gc** [comment]
With no response from the creator, and it seeming like this is only for BSO, im closing this PR. As jonesey said, if this is only for BSO, it should be PR'd in a way to bso.

**Pull request closed without merging**
