### PR TITLE
Corrupt gauntlet

### PR DESCRIPTION
**Pull request by coolbop32**
### Description:

Update time to be more accurate.

### Changes:

Made it so you can make the new weapons
Made skilling reqs same as in game
Made time more accurate

### Other checks:

-   [x] I have tested all my changes thoroughly.

### CODE REVIEW

**Comment by gc** [comment]
Does this need to be updated to the new osjs version?

**Comment by coolbop32** [comment]
> Does this need to be updated to the new osjs version?

yes

**Review by gc — CHANGES_REQUESTED** [review]
This should be updated, and tested to make sure its alright (after having updated it)

**Comment by coolbop32** [comment]
> This should be updated, and tested to make sure its alright (after having updated it)

updated

**Pull request merged**
