### PR TITLE
Add open all, any and until master

### PR DESCRIPTION
**Pull request by LuxrayElite**
### Description:

Original PR: #2235 
Author @Lilylicious 

Repull was with permission from Lily
Nerfed --all and updated conflicts
Further nerfing could easily be applied.

Partially solves the issues: #2743 #2185

### Changes:

Open --all, opening an owned number of a single openable (requires name variable)

Open --any, opens an owned number of first openable in the +open list (doesn't require name)

Open --master, open until a master clue is found. (requires name variable)

### Other checks:
image
image

-   [x] I have tested all my changes thoroughly.

### CODE REVIEW

**Review by Lilylicious — APPROVED** [review]
Looks good to me.

**Comment by LuxrayElite** [comment]
Consolidated duplicate code into a single function
Fixed issues related to merging into a function

**Review by orsou — APPROVED** [review]
This would save us so much typing!

**Comment by LuxrayElite** [comment]
Changes since draft:
Experimented with limit restrictions; chose not to impose based on other commands response time
Updated to match changes implemented by loot tracking commit
Played around with code structure so only 1 additional function is now implemented. The rest is added onto the default functions

Its been requested to implement true openAll... (rather than limited to an item which I nerfed it too)
OpenAll implings
Open implings until clue.

Would also make a BSO PR for this to remove --master restrictions along with an update to =create for being able to create

**Comment by LuxrayElite** [comment]
Closed due to rewrite by Magna

**Pull request closed without merging**
