### PR TITLE
Added XP value to lamps as subtext & jmod

### PR DESCRIPTION
**Pull request by TURB042O**
### Description:

- Tiny, small, average, large & huge lamps to display xp value on bank image & added subtext to JMod

### Changes:

- added a new section for XP Lamps adding the xp value as subtext for each lamp.
- added JMod to the Scythe of vitur (JMod) to easily tell it apart from the rest.

### Other checks:

- [x] I have tested all my changes thoroughly.

### CODE REVIEW

**Comment by TURB042O** [comment]
I am new at this so sorry for the multiple PR, but once I figured some of the commits I had made weren't going where they should have been I didn't want to risk it so I made a new PR but with all the same changes, put in the right place.

**Comment by LuxrayElite** [comment]
> added uncharged to the uncharged versions of sanguinesti staff & Scythe of vitur.

This could also be merged to osb as a useful addition. Meaning it could be removed from this pr and a new pr on master branch (osb) then the commit would be merged over leaving only bso specific things in this pr.

**Comment by TURB042O** [comment]
> > added uncharged to the uncharged versions of sanguinesti staff & Scythe of vitur.
> 
> This could also be merged to osb as a useful addition. Meaning it could be removed from this pr and a new pr on master branch (osb) then the commit would be merged over leaving only bso specific things in this pr.
> 

I could totally do this... you're talking about the uncharged stuff right

**Comment by TURB042O** [comment]
@TastyPumPum ty SO very much for what you did! for real

**Comment by TURB042O** [comment]
@themrrobert can you look at this & merge it if all checks out?

**Comment by gc** [comment]
Implemented differently here: https://github.com/oldschoolgg/oldschoolbot/commit/b17089dd7784cfe1c91b01b6109afe1222d030b3

**Comment by TURB042O** [comment]
> Implemented differently here: https://github.com/oldschoolgg/oldschoolbot/commit/b17089dd7784cfe1c91b01b6109afe1222d030b3

No way you were able to do that all within one line of code that's awesome

**Pull request closed without merging**
