### PR TITLE
Fix pluralisation on smithing items without required level

### LINKED ISSUE #4879: arrowtips typo
image

### PR DESCRIPTION
**Pull request by osrsjobbo**
### Description:

Smithing items are inconsistently named, for example: `Steel Axe`, `Steel Arrowtips`, `Adamantite nails`. As per #4879 sometimes the smithing without level error results in a double 'ss'.  This fixes that by checking if the item name is already pluralised. 

This closes #4879.

image

### Changes:

- Changed the output of 's' to be dependant on last character of smithed item. 

### Other checks:

-   [X] I have tested all my changes thoroughly.

### CODE REVIEW

**Comment by Lajnux** [comment]
For consistency we should just make this a function and use it everywhere that something is fletched, crafted, smithed etc

**Comment by osrsjobbo** [comment]
@Lajnux Done that and fixed every issue I could find.

**Comment by gc** [comment]
Even though its a simple function, would be nice to have tests for `pluraliseItemName`.

**Comment by osrsjobbo** [comment]
Hopefully that is OK. Feedback appreciated.

**Review by gc — CHANGES_REQUESTED** [review]
put the function in smallUtils, and put the tests in util.test.ts

**Comment by osrsjobbo** [comment]
Done & all checks passing now.

**Comment by gc** [comment]
This has many conflicts now, FYI.

**Pull request closed without merging**
