### PR TITLE
adjust expire time shootingstar

### PR DESCRIPTION
**Pull request by Lajnux**
### Description:

Adjusted the expire length slightly and made it also scale for patron tiers to be more reasonable. 

### Changes:

Adjusted the expire length slightly and made it also scale for patron tiers to be more reasonable. 

### Other checks:

-   [x] I have tested all my changes thoroughly.

### CODE REVIEW

**Comment by themrrobert** [comment]
Since shooting stars are AFK, why not make them 2x max trip length like other 'AFK' stuff such as alching + cannonballs?

**Comment by Lajnux** [comment]
> Since shooting stars are AFK, why not make them 2x max trip length like other 'AFK' stuff such as alching + cannonballs?

I didn't think about that tbh, and it's doable but would be slight spaghetti code in the determineMineFunction

**Comment by themrrobert** [comment]
> > Since shooting stars are AFK, why not make them 2x max trip length like other 'AFK' stuff such as alching + cannonballs?
> 
> I didn't think about that tbh, and it's doable but would be slight spaghetti code in the determineMineFunction

I would just take whatever `determineMineFunction` returns and multiply it by 2.

However idk if people would even want to spend that much time at a shooting star 🤷

**Comment by Lajnux** [comment]
> > > Since shooting stars are AFK, why not make them 2x max trip length like other 'AFK' stuff such as alching + cannonballs?
> > 
> > 
> > I didn't think about that tbh, and it's doable but would be slight spaghetti code in the determineMineFunction
> 
> I would just take whatever `determineMineFunction` returns and multiply it by 2.
> 
> However idk if people would even want to spend that much time at a shooting star 🤷

Yea then we would have to double the output, but it wouldn't really be accurate doing that since shooting stars have layers and then the outcome would kinda screw with the whole layer simulation. I think it's fine as is but the expire length def needs this slight length increase.

**Comment by themrrobert** [comment]
I approve these changes as-is

**Pull request merged**
