### PR TITLE
Adding kill simulation for nex

### PR DESCRIPTION
**Pull request by TURB042O**
### Description:

When you currently `/kill name:nex` you get the error return `I don't have that monster` so hopefully this fixes that issue

### Other checks:

- [ ] I have tested all my changes thoroughly.

### CODE REVIEW

**Comment by nwjgit** [comment]
This wont simulate any of the unique items. This is due to Nex's unique items being handled outside of a standard LootTable().

I've been meaning to fix Moktang having an unlimited /kill quantity, I can PR a fix and add nex in there too.

**Comment by TURB042O** [comment]
> This wont simulate any of the unique items. This is due to Nex's unique items being handled outside of a standard LootTable().
> 
> I've been meaning to fix Moktang having an unlimited /kill quantity, I can PR a fix and add nex in there too. 

alright. thanks

**Comment by gc** [comment]
Do you have a test bot youre actually testing this on?

**Comment by TURB042O** [comment]
> Do you have a test bot youre actually testing this on?

no. that's the next thing to figure out via mobile.  but cyr was working with me on this

**Comment by nwjgit** [comment]
This PR here: https://github.com/oldschoolgg/oldschoolbot/pull/5638 should handle Nex `/kill` unless there was something more you wanted to do with Nex.

**Comment by TURB042O** [comment]
> This PR here: https://github.com/oldschoolgg/oldschoolbot/pull/5638 should handle Nex `/kill` unless there was something more you wanted to do with Nex.

nothing more. I just wanted to get the simations to not say I don't have this monster

**Pull request closed without merging**
