### PR TITLE
Changes to CPETS & DCPETS 

### PR DESCRIPTION
**Pull request by TURB042O**
### Description:

made all pets except leagues pet bank value 1m, changed some pets from `Coal` to `Herbi` to register as a pet.

### Changes:

- Changed `Coal` to `Herbi` on Rudolph & bv 1m
- ~~made doopy tradeable GE only~~
- doopy is tradeable via player & ge.
- all pets in customitems that are labeled `Herbi` are now 1m bv
- Removed tradeable: true & tradeable_on_ge: true from Balloon cat due to it is ment to be untradeable and has the super untradeable code also.
- moved Balloon cat out of discontinued section in pets.ts above dyed
- ~~removed `cantBeSacrificed: true` from the guthix, saradomin & zamorak pets.~~
- ~~removed `cantBeSacrificed: true` from Buggy~~
- turned Skip from `Coal` to `Herbi` because it is a growable pet.

- Added `isDiscontinued: true` to casper, doopy & mini mortimer

### Other checks:

- [ ] I have tested all my changes thoroughly.

### CODE REVIEW

**Comment by gc** [comment]
You should try to split up PRs a bit if theyre like this, you have some changes in here that probably shouldnt be mixed together (like making doopy only tradeable on g.e?, and the cantBeSacrificed changes. You'd have to remove those for me to merge this.

**Comment by TURB042O** [comment]
> You should try to split up PRs a bit if theyre like this, you have some changes in here that probably shouldnt be mixed together (like making doopy only tradeable on g.e?, and the cantBeSacrificed changes. You'd have to remove those for me to merge this.

okay

**Comment by TURB042O** [comment]
> You should try to split up PRs a bit if theyre like this, you have some changes in here that probably shouldnt be mixed together (like making doopy only tradeable on g.e?, and the cantBeSacrificed changes. You'd have to remove those for me to merge this.

okay so I did as you said.  didn't really know how to split this one up since it is already done, but I edited this one and posted the changes in the description. 

also I made #5701

**Comment by TURB042O** [comment]
> You should try to split up PRs a bit if theyre like this, you have some changes in here that probably shouldnt be mixed together (like making doopy only tradeable on g.e?, and the cantBeSacrificed changes. You'd have to remove those for me to merge this.

okay so I did as you said.  didn't really know how to split this one up since it is already done, but I edited this one and posted the changes in the description. 

also I made #5701

**Comment by TURB042O** [comment]
ugh I'm just messing up

**Pull request closed without merging**
