### PR TITLE
Fixed only lowercase searches in CL issue

### PR DESCRIPTION
**Pull request by TURB042O**
### Description:

right now searching any CL if you start your search using a capital letter for example `Halloween`.. no results show.   but when you type `halloween` all the halloween results show. this should fix that.

### Changes:

- changed `(value)` to `(value.toLowerCase)`

### Other checks:

- [ ] I have tested all my changes thoroughly.

### CODE REVIEW

**Comment by nwjgit** [comment]
What were you trying to accomplish here exactly? `/cl name:` already isn't case sensitive and you can do `/cl name: nex` or `/cl name: Nex` or even `/cl name: NeX` and all three return the Nex collection log.

**Comment by DayV-git** [comment]
This change is for the autocomplete function, if you type `/cl name: nex`, nothing will come up at the moment in the search

**Comment by nwjgit** [comment]
> This change is for the autocomplete function, if you type `/cl name: nex`, nothing will come up at the moment in the search

Ah I see that now, thanks for clarifying.

**Comment by TURB042O** [comment]
> What were you trying to accomplish here exactly? `/cl name:` already isn't case sensitive and you can do `/cl name: nex` or `/cl name: Nex` or even `/cl name: NeX` and all three return the Nex collection log.
> 
> If there is a certain cl that isn't working properly then it is more likely an issue with it's aliases. 

sorry I am just now seeing this comment. idk why but github mobile has never notified for comments :( so thank you @DayV-git for responding :) 

but not sure if this has gone live yet or not haven't had chance to check but here are screen shots of what I'm hoping to achieve.



this is with capital H (just like the cl is labeled) nothing shows.



now I retype it with lowercase h and here's all halloweens.. thats just the example I choose to use.

**Comment by TURB042O** [comment]
so I'm guessing this didn't fix anything because the issue I'm trying to fix still exists.

maybe somebody will know the answer? @nwjgit @gc 


the issue is that I've noticed only in /cl the searching is case sensitive 


because anywhere else capitals don't matter 


what's causing this?

**Pull request merged**
