### PR TITLE
Completion cape adjustments

### PR DESCRIPTION
**Pull request by nwjgit**
### Description:
- Various adjustments and corrects for completion cape

### Changes:
- Add the music cape requirements check to music cape(t) /buy
  - Music cape(t) can be purchased if the user received a music cape from boxes and has max qp/diaries. This negates all the requirements for completing everything under music cape.
- Add a new comp check for music cape being bought with /buy
- Make spooky graceful dc and remove it from the graceful cl 
- Remove `Partyhat set` & `Partyhat & specs` from cl creatables and move to christmas cracker cl

### Other checks:
- [X] I have tested all my changes thoroughly.

addresses: https://github.com/oldschoolgg/oldschoolbot/issues/5587

### CODE REVIEW

**Comment by gc** [comment]
`Remove Partyhat set & Partyhat & specs from cl creatables and move to christmas cracker cl` 

Did people vote/agree with this?

**Comment by DarkBugz** [comment]
> `Remove Partyhat set & Partyhat & specs from cl creatables and move to christmas cracker cl`
> 
> Did people vote/agree with this?

This is an integrity change. It follows the same logic as why we moved phats to their own log in the first place. These 2 items in creatables log prevents irons from finishing comp t.

**Comment by DarkBugz** [comment]
https://discord.com/channels/342983479501389826/1032668754561224734/1237853125767860305

It also did pass a poll

**Comment by nwjgit** [comment]
> `Remove Partyhat set & Partyhat & specs from cl creatables and move to christmas cracker cl`
> 
> Did people vote/agree with this?

Removing them was defiantly polled and agreed upon multiple times in discussion/polls.  Adding the two items to Christmas cracker cl was news to me, I can run a poll for this specific change if you want.

**Pull request merged**
