### PR TITLE
Add auto farm button to check patches

### PR DESCRIPTION
**Pull request by osrsjobbo**
### Description:

Add an auto farm button on /farming check_patches when patches are complete and ready to be harvested. 

image

I am nervous about how I have used BaseMessageOptions to allow me to return buttons here, in addition whilst I was using /m as inspiration, I couldn't get it to return a promise like /m does. Would appreciate a set of eyes on this.  That said, everything seems to work OK. 

### Changes:

- Add auto farm button to /check_patches response

### Other checks:

-   [X] I have tested all my changes thoroughly.

### CODE REVIEW

**Comment by gc** [comment]
Autofarm shouldnt have the seed pack icon. The farming icon is more appropriate.

**Comment by osrsjobbo** [comment]
Done & rebased with master

**Comment by gc** [comment]
Failing due to circular imports (pull my last commit, run yarn test, and check the error - ping me on discord for help if you need, usually the fix is moving something to a different file)

**Comment by osrsjobbo** [comment]
fixed

**Pull request merged**
