### PR TITLE
Add Drystreak Evil Chicken Outfit

### PR DESCRIPTION
**Pull request by TastyPumPum**
Adds the ability to check drystreak on eggs offered for the evil chicken outfit. 

-   [x] I have tested all my changes thoroughly.

### CODE REVIEW

**Review by gc — CHANGES_REQUESTED** [review]
I dont see any testing of this in the testing server?

**Comment by TastyPumPum** [comment]
> I dont see any testing of this in the testing server?

Sorry tested in my own server a lot last night, will test it in the testing server tonight

**Comment by TastyPumPum** [comment]
> I dont see any testing of this in the testing server?

Now been tested in the testing server, and JustMart helped tidy it.

**Comment by gc** [comment]
@TastyPumPum conflicts

**Comment by TastyPumPum** [comment]
> @TastyPumPum conflicts


Conflicts have been resolved

**Pull request merged**
