### PR TITLE
BSO - added range cape check to reduce arrow & dart cost

### LINKED ISSUE #3827: Ranged Master Cape at Inferno
## 🐛 Bug Report

Write a description of the bug here, give all the information you can about what it is, how it happened.
It does not appear as if the ranged master cape ammo saving perk works on normal inferno. 

With Ranged Master Cape: 
image

With Assembler:
image

### PR DESCRIPTION
**Pull request by lordzuku**
### Description:
added master range cape effect to work on zuk

### Changes:

passed a boolean for if a master range cape is worn to the cost object, checked if true & then modified the cost per hour for darts & arrows
### Other checks:

-   [Y ] I have tested all my changes thoroughly.
fixes 
#3827 
#3618

### CODE REVIEW

**Comment by 6enny6** [comment]
should this be added to lib/data/similaritems.ts ?

**Comment by lordzuku** [comment]
> should this be added to src/lib/data/similaritems.ts ?
> 
> make ranger master act as an assembler

iirc the range max cape shouldnt act as an assembler, otherwise the ammo saving bonuses might stack, would probably need it coded into future commands as a separate ammo saving systems

**Comment by anthonyburrow** [comment]
> would probably need it coded into future commands as a separate ammo saving systems

I believe this already exists in the "specialRemoveItems" function which is called in inferno.ts, however it only accounts for the Assembler:

https://github.com/oldschoolgg/oldschoolbot/blob/10a15038ed377c1a6f5f0a43c466973b030c7e96/src/extendables/User/Bank.ts#L142

I would probably recommend making this function more generalized for BSO additions by adding the Ranged Master Cape percentage in this cost function instead of making a new condition for just the inferno.

**Comment by lordzuku** [comment]
> > would probably need it coded into future commands as a separate ammo saving systems
> 
> I believe this already exists in the "specialRemoveItems" function which is called in inferno.ts, however it only accounts for the Assembler:
> 
> https://github.com/oldschoolgg/oldschoolbot/blob/10a15038ed377c1a6f5f0a43c466973b030c7e96/src/extendables/User/Bank.ts#L142
> 
> I would probably recommend making this function more generalized for BSO additions by adding the Ranged Master Cape percentage in this cost function instead of making a new condition for just the inferno.

unless im mistaken (which i might be, just recently started looking over the project)
that would only apply for regular m k trips & would still need a manual patch for fixing the inferno.

currently there is an already built system for m k trips for range cape saving

**Pull request closed without merging**
