### PR TITLE
Food updates for consistency

### PR DESCRIPTION
**Pull request by osDreamscape**
Add 3% boost to all "22" healing foods including tuna potatoes, instead of just manta rays, added 2% boost to other "20" healing foods, including mushroom potatoes, rather than just sharks, moved 1% boost from "16" heal monkfish to karambwans "18" heal + 1t less eating delay, and in line with food tiers.

### Other checks:

-   [ ] I have tested all my changes thoroughly.

### CODE REVIEW

**Comment by Lajnux** [comment]
Looks good to merge

**Review by Lajnux — APPROVED** [review]
This PR looks solid and good.

**Comment by osrsjobbo** [comment]
@gc  Any input about your concerns with this PR? If so I can look to update it so it can get merged. 

Should we be boosting two click items (eg summer pie)?

**Comment by gc** [comment]
I can't update/merge this PR because you deleted your repo.

**Pull request closed without merging**
