### PR TITLE
Add the runecrafting of tiaras

### PR DESCRIPTION
**Pull request by TastyPumPum**
Adds the option to runecraft tiaras. Gives the relevant rc xp and takes the relevant cost, provides the relevant loot. 

Couple of tiaras are needed for the stash units which was the prompt of this pr.

-   [x] I have tested all my changes thoroughly.

### CODE REVIEW

**Comment by themrrobert** [comment]
What is the XP/hr if you make a full trip of Cosmic or Death tiara's for example?

**Comment by Lajnux** [comment]
I would love to see xp/hours at different levels, also seems to be similar boosts etc to the runecraft command so can't both be in same activity?

**Comment by TastyPumPum** [comment]
> What is the XP/hr if you make a full trip of Cosmic or Death tiara's for example?
Pure rc xp is as follows -
Death tiaras - 39k an hour
Cosmic tiaras - 31k an hour

You can do 777 tiaras an hour at both of them. 

The time consuming part would be getting the tiara's and talismans ofcourse
Assuming you have silver bars banked and that's not time loss. 
777 tiaras take 26 and a half minutes to craft.

Now to add on getting the talismans a death talisman is only obtainable currently through dark beasts at a rate of 1 in 128, so you'd need to kill 99,456 on average. Killing 100 an hour (it's roughly around 97) this would take 994 hours, on average. Cosmic talismans have a few more sources, but out right grinding them we can say abyssal demons at the same rate as death talismans. We can kill say 200 abby demons an hour (think its more like 160 an hour) Thats 497 hours of grinding abby demons. Even saying you can get half the talismans from dailies/random events while grinding thats 248 hours. 

So this then gives death talismans about 26 runecraft xp/hr.
So this then gives cosmic talismans about 125 runecraft xp/hr.

In no way will this PR be a good method of training.

**Comment by TastyPumPum** [comment]
> I would love to see xp/hours at different levels, also seems to be similar boosts etc to the runecraft command so can't both be in same activity?

It probably would be cleaner to have it in the same activity, but I felt more comfortable testing it and getting it working like this way, I'm happy for someone else to take over the PR though

**Comment by themrrobert** [comment]
> > I would love to see xp/hours at different levels, also seems to be similar boosts etc to the runecraft command so can't both be in same activity?
> 
> It probably would be cleaner to have it in the same activity, but I felt more comfortable testing it and getting it working like this way, I'm happy for someone else to take over the PR though

Being in the RC command would probably be best, but if magna's okay with it then idm.

But what about the xp/hr for like earth/fire tiaras ? where you can get greater quantities of them from like dks etc. my guess is that would be the BIS XP until a certain point. Which isn't necessarily bad, just worth knowing if you don't mind running that number, too, please? Ty :)

**Comment by TastyPumPum** [comment]
> > > I would love to see xp/hours at different levels, also seems to be similar boosts etc to the runecraft command so can't both be in same activity?
> > 
> > 
> > It probably would be cleaner to have it in the same activity, but I felt more comfortable testing it and getting it working like this way, I'm happy for someone else to take over the PR though
> 
> Being in the RC command would probably be best, but if magna's okay with it then idm.
> 
> But what about the xp/hr for like earth/fire tiaras ? where you can get greater quantities of them from like dks etc. my guess is that would be the BIS XP until a certain point. Which isn't necessarily bad, just worth knowing if you don't mind running that number, too, please? Ty :)

The pure rc xp/hrs are below assuming you have the tiaras and talismans:
Air Tiara's - 25k
Blood Tiara's - 54k
Body Tiara's - 38k
Chaos Tiara's - 22k
Cosmic Tiara's - 31k
Death Tiara's - 39k
Earth Tiara's - 33k
Fire Tiara's - 36k
Law Tiara's - 28k
Mind Tiara's - 28k
Nature Tiara's - 31k
Water Tiara's - 31k
Wrath Tiara's - 54k

Sorry for the delay forgot to come back to this, again these xp/hrs assume you have the tiara's and talismans banked which is the tedious part.

**Comment by TastyPumPum** [comment]
Added the single tick time to create each tiara as I forgot you cant do the whole inventory in one click like you can for runecrafting. Which someone bought up in testing.
New pure xp/hr rates are -
Air Tiara's - 22k
Blood Tiara's - 46k
Body Tiara's - 33k
Chaos Tiara's - 20k
Cosmic Tiara's - 28k
Death Tiara's - 35k
Earth Tiara's - 28k
Fire Tiara's - 30k
Law Tiara's - 26k
Mind Tiara's - 24k
Nature Tiara's - 27k
Water Tiara's - 26k
Wrath Tiara's - 46k

Again these xp/hrs assume you have the tiara's and talismans banked which is the tedious part.

**Comment by TastyPumPum** [comment]
Tested by myself since the conflicts and back working again.

**Comment by TastyPumPum** [comment]
Back working with the latest conflicts.

**Review by gc — CHANGES_REQUESTED** [review]
Same kind of issue as the other PR.. should be its own activity. if theyre entirely separate in a if/else case, theres no reason to put them together ilke this. and they dont need to be in the same activity to be in the same command.

**Comment by TastyPumPum** [comment]
Moved into it's own activity

**Pull request merged**
