### PR TITLE
Fix mysterious tree contracts

### PR DESCRIPTION
**Pull request by nwjgit**
### Description:
Fixes an issue causing mysterious tree contracts to not properly multiple the seed packs & non mystery box loot. 
Fixes the wording in the Jane message

### Changes:
- remove plantsNotUsedForArcaneHarvester
- Make Mysterious tree contracts give an extra seed pack by default to make them give four total with max boosts to match other contracts.
- Add a return to the final handleTripFinish to remove the eslint warning
- Fix the Jane chatHeadImage() for farming contracts to show the correct amount of seed packs received. 
- Remove outdated plopper message "You recieved 100% bonus loot from Plopper" (seen below) since the "100% for Plopper" message is already shown

### Other checks:
- [X] I have tested all my changes thoroughly.
closes: https://github.com/oldschoolgg/oldschoolbot/issues/5523

Discord_viM1SQmy4A

### CODE REVIEW

**Comment by themrrobert** [comment]
Just take out the plantsNotUsedForArcaneHarvester code entirely.

The mystery boxes from Mysterious trees  are handled after the loot multiplication anyway, with the current code, mysty trees will still only give 3 instead of 4 seed packs.

So just remove the:
```ts
const plantsNotUsedForArcaneHarvester = ['Mysterious tree'].map(i => Farming.Plants.find(p => p.name === i)!);
assert(!(plantsNotUsedForArcaneHarvester as any[]).includes(undefined));
```
from the top of the file, and then the surrounding logic referencing that const in your modified code.

The farming code still needs more refactoring before we should be using code like this, since it's not doing it's intended job, and only having negative side effects.

**Comment by nwjgit** [comment]
> Just take out the plantsNotUsedForArcaneHarvester code entirely.
> 
> The mystery boxes from Mysterious trees are handled after the loot multiplication anyway, with the current code, mysty trees will still only give 3 instead of 4 seed packs.
> 
> So just remove the:
> 
> ```ts
> const plantsNotUsedForArcaneHarvester = ['Mysterious tree'].map(i => Farming.Plants.find(p => p.name === i)!);
> assert(!(plantsNotUsedForArcaneHarvester as any[]).includes(undefined));
> ```
> 
> from the top of the file, and then the surrounding logic referencing that const in your modified code.
> 
> The farming code still needs more refactoring before we should be using code like this, since it's not doing it's intended job, and only having negative side effects.

I thought the same thing but didn't want to remove pre-existing code, I'll make the change now.

**Comment by nwjgit** [comment]
> Just take out the plantsNotUsedForArcaneHarvester code entirely.
> 
> The mystery boxes from Mysterious trees are handled after the loot multiplication anyway, with the current code, mysty trees will still only give 3 instead of 4 seed packs.
> 


Also we may want to rethink the solution here because since mystery tree loot is pretty worthless, and people only do it for the boxes. Removing this code will make arcane harvester work with mystery trees and remove mats unnecessarily. This could be circumvented by toggling it off but that would drastically hurt qol doing that each farm run.

**Comment by nwjgit** [comment]
I changed it around so that Mysterious trees don't use Arcane harvester since this is how it's worked for awhile and the base loot is really bad and it just wastes invention materials for no real gain. Added new code to make Mysterious trees give an extra seed pack for contracts. This makes it so that even without Arcane harvester mysterious tree contracts still get 4 seed packs at max boost. This makes the default 2 seed packs per mysterious tree contract.

**Pull request merged**
