### PR TITLE
XP from Tears of Guthix

### PR DESCRIPTION
**Pull request by nwjgit**
### Description:
Data command for XP received from tears of Guthix
### Changes:
- Add `/data name: XP from Tears of Guthix`
### Other checks:
- [X] I have tested all my changes thoroughly.
Discord_UbXx1nth97

### CODE REVIEW

**Comment by gc** [comment]
This is global XP from tears of guthix. If thats intentional, it should say global. If its meant to be per-user, it should be changed to do that.

**Comment by nwjgit** [comment]
> This is global XP from tears of guthix. If thats intentional, it should say global. If its meant to be per-user, it should be changed to do that.

Thanks for the catch, I added the check for user id. It's intended to be per-user and not global. Although I could add another one in for global if you'd like.

**Review by gc — CHANGES_REQUESTED** [review]
The title needs to be changed to say "personal" too

**Comment by nwjgit** [comment]
> The title needs to be changed to say "personal" too

done.

**Pull request merged**
